stages:
  - syntax
  - build
  - test
  - deploy

syntax:
  stage: syntax
  except:
    - master
  script:
    - "php /var/www/migration-tools/bin/ci/jobs/syntaxCheck.php $CI_COMMIT_REF_NAME $CI_COMMIT_SHA $CI_COMMIT_BEFORE_SHA"

build:
  stage: build
  script:
    - "php /var/www/migration-tools/bin/ci/jobs/prepareTests.php $CI_PROJECT_NAME $CI_COMMIT_REF_NAME"

test:
  stage: test
  script:
    - "php /var/www/migration-tools/bin/ci/jobs/runTests.php"

deploy:
  stage: deploy
  only:
    - develop
  script:
    - "php /var/www/migration-tools/bin/ci/jobs/deployStaging.php $CI_COMMIT_REF_NAME"
